import "@/assets/scss/app.scss";
import {Toaster} from "@/components/ui/toaster";
import Header from "@/layouts/auth/header"
import Footer from "@/layouts/auth/footer"
import {AuthContextProvider} from "@/context/auth-context"
import {auth} from "auth"

export const metadata = {
    title: 'Authentication',
    description: 'Generated by Next.js',
}


import SessionProvider from "@/components/providers/session-provider"
import {getServerSession} from "next-auth/next"
import {authOptions} from "@/app/api/auth/[...nextauth]/route"

export default async function RootLayout({
                                             children,
                                         }: {
    children: React.ReactNode
}) {
    const session = await getServerSession(authOptions)
    console.log(session, ' ----session')
    return (
        <html lang="en">
        <body>
        <Header/>
        <div vaul-drawer-wrapper="">
            <main className="relative flex min-h-screen flex-col bg-background">
                <SessionProvider session={session}>
                    {children}
                </SessionProvider>
            </main>
        </div>
        {/*<Footer/>*/}
        <Toaster/>
        </body>
        </html>
    )
}
