import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "@/public/globals.css";
import { Inter as FontSans } from "next/font/google";
import { cn } from "@/lib/utils";
import Header from "@/layouts/dashboard/header";
import Sidebar from "@/layouts/dashboard/sidebar";
import Providers from "@/components/providers/session-provider";
import { Toaster } from "@/components/ui/toaster";

const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
});

const inter = Inter({ subsets: ["latin"] });
export const metadata: Metadata = {
  title: "Event Wizz App",
  description: "Generated by create next app",
};
import { getServerSession } from "next-auth";
import { authOptions } from "@/app/api/auth/[...nextauth]/route"
import SessionProvider from "@/components/providers/session-provider"

export default async function DashboardLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getServerSession(authOptions)
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={cn(
          "min-h-screen bg-background font-sans antialiased",
          fontSans.variable
        )}
      >
          <SessionProvider session={session}> 
          <Toaster />
          <Header />
          <section className="flex h-screen overflow-hidden">
            <Sidebar />
            <main className="w-full pt-16">{children}</main>
          </section>
        </SessionProvider>
      </body>
    </html>
  );
}
